const regexs = {
    r_READ : /IDENTIFIER(SEMI)/,
    r_WRITE : /(NUMBER|IDENTIFIER)(SEMI)/,
    r_ASSIGN : /\bIDENTIFIER(IDENTIFIER|NUMBER)((PLUS|MULT|MINUS)(IDENTIFIER|NUMBER))?\)?SEMI\b/,
    r_UNTIL : /(IDENTIFIER|NUMBER)(LESSTHAN|EQUAL)(IDENTIFIER|NUMBER)SEMI/,
    r_REPEAT : /((?!SEMI).)*UNTIL/,
    r_IF : /(NUMBER|IDENTIFIER)(LESSTHAN|EQUAL)(NUMBER|IDENTIFIER)THEN(.+)?END/,    
}


module.exports = regexs ;
